name: Secrets                           # ワークフロー名
on: push                                # イベント（プッシュ時に起動）
jobs:                                   # ジョブの定義
    print:                              # ジョブID
        runs-on: ubuntu-latest          # ランナー（Ubuntuで実行）
        env:
            PASSWORD: ${{ secrets.PASSWORD}}            # Secretsの参照
        steps:
            - run: echo "${PASSWORD}"                   # ログ出力はマスクされる
            - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # ログ出力はマスクされない